kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
    app: consul-client
  name: consul-client-ds
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: consul-client
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consul-client
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: consul-client
        image: registry.dev.chelizitech.com/public/consul:1.2.2
        command: ["consul","agent","-data-dir=/tem/consul","-advertise=$(MY_HOST_IP)","-retry-join=10.9.50.2","-retry-join=10.9.50.3","-retry-join=10.9.50.4","-datacenter=saas-test"]
        env:
        - name: CONSUL_LOCAL_CONFIG
          value: '{"leave_on_terminate": true}'
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      imagePullSecrets:
      - name: regcred
